all_charts:
	rm -f charts/*.png
	./histogram.py 1
	./histogram.py 2 'str(int(x)/10)' '"%s0-%s9" % (x, x)'
	./bar.py 3 10
	./bar.py 11 14
	./other.py 15
	./histogram.py 16
	./other.py 17
	./bar.py 18 25
	./other.py 26
	./bar.py 27 29
	./other.py 30
	./other.py 31
	./histogram.py 32
	./histogram.py 33
	./histogram.py 34
	./histogram.py 35
	./histogram.py 36
	./bar.py 37 41
	./other.py 42
	./other.py 43
	./bar.py 44 48
	./other.py 49
	./histogram.py 50
	./bar.py 51 55
	./other.py 56
	./histogram.py 57
	./histogram.py 58
	./histogram.py 59
	./histogram.py 60
	./histogram.py 61
	./histogram.py 62
	./bar.py 63 67
	./other.py 68
	./histogram.py 69
	./other.py 70
	./other.py 71
	./other.py 72
	./other.py 73
	./histogram.py 74
