site_name: Zero Install Docs
site_url: https://0install.net/
repo_url: https://github.com/0install/docs
edit_uri: blob/master/docs/

copyright: >
  © Copyright 2003-2024 Thomas Leonard, Bastian Eicher and others<br>
  Permission is granted to use the documentation in accordance with the terms of the <a href="https://creativecommons.org/licenses/by-sa/2.5/">Creative Commons Attribution-ShareAlike 2.5 license</a>.

theme:
  name: material
  logo: img/logo.png
  favicon: favicon.ico
  font: false
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

extra_css: [style.css]

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        perspectives.md: about/perspectives.md
        comparison.md: about/comparison.md
        features.md: about/features.md
        faq.md: about/faq.md
        basics/making-shortcuts.md: basics/menu.md
        basics/using-apps.md: details/apps.md
        basics/windows.md: details/desktop-integration.md
