site_name: Zero Install
site_favicon: img/logo.png
#site_url: https://docs.0install.net/
repo_url: https://github.com/0install/docs

theme: readthedocs
extra_css: [extra.css]
markdown_extensions: [def_list]
plugins: []
